
clean:
	rm -f *.o hashtest unit_tests utils hash_table

memhashtest: hashtest
	valgrind --leak-check=full ./hashtest

hashtest: hashtable.o unit_tests.o linked_list.o common.o
	gcc -g -Wall unit_tests.c -lcunit hash_table.c linked_list.c common.c -o hashtest

hashtable.o: hash_table.c hash_table.h linked_list.h iterator.h common.h
	gcc -c -g -Wall hash_table.c

common.o: common.c common.h
	gcc -c -g -Wall common.c

unit_tests.o: unit_tests.c common.h
	gcc -c -g -Wall unit_tests.c

memlinktest: linktest
	valgrind --leak-check=full ./linktest

linktest: linked_list.o linked_test.o common.h
	gcc -g -Wall linked_test.c -lcunit linked_list.c common.c -o linktest

linked_list.o: linked_list.c linked_list.h iterator.h common.h
	gcc -c -g -Wall linked_list.c

linked_test.o: linked_test.c
	gcc -c -g -Wall linked_list.c
	
freqtest: freq-count.o hashtable.o unit_tests.o linked_list.o common.o
	gcc -g -Wall freq-count.c -lcunit hash_table.c linked_list.c common.c -o freqtest

memfreqtest: freqtest
	valgrind --leak-check=full ./freqtest 16k-words.txt

freq-count.o: freq-count.c common.h iterator.h linked_list.h hash_table.h
	gcc -c -g -Wall freq-count.c

hash_coverage: hashtable.o unit_tests.c linked_list.o common.o 
	gcc -Wall -fprofile-arcs -ftest-coverage unit_tests.c -lcunit linked_list.c common.c hash_table.c -o hash_coverage

list_coverage: hashtable.o linked_list.o common.o linked_test.c
	gcc -Wall -fprofile-arcs -ftest-coverage linked_test.c -lcunit linked_list.c common.c hash_table.c -o link_coverage

run_hash_cov: hash_coverage
	./hash_coverage
	gcov hash_coverage-hash_table.gcno

run_link_cov: link_coverage
	./link_coverage
	gcov link_coverage-linked_list.gcno